require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '15.1'
prepare_react_native_project!

use_frameworks! :linkage => :static

target 'StudyVault' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  

  post_install do |installer|
    react_native_post_install(installer)
  end
end